### ISSUE TITLE
Add support for digest signing and Rustcrypto `DigestSigner` trait

### ISSUE THREAD

**Issue by Erik1000** [jedisct1/rust-ed25519-compact#14]
We want to use `ed25519-compact` as an alternative for `ed25519-dalek`  in our [open source JOSE implementation](https://github.com/minkan-chat/jose/) since the dalek project seems kind of dead and has outdated dependencies. For our migration, we need a [`DigestSigner`](https://docs.rs/signature/latest/signature/trait.DigestSigner.html) implementation, would it be possible for this crate to add this implementation?

**Comment by jedisct1** [comment]
I don't really understand what a `DigestSigner` is, at least not in this context.
Unlike ECDSA, EdDSA doesn't sign a hash of the message.

Can you clarify what problem you are trying to solve?

If the message must be provided as multiple chunks instead of a single part, there's a [streaming API](https://github.com/jedisct1/rust-ed25519-compact#incremental-api-example-usage).

**Comment by tarcieri** [comment]
`DigestSigner` is the IUF API, accepting an instance of `digest::Digest`, then finalizing and signing the resulting hash.

As such it most cleanly maps to Ed25519ph, which may not be what people actually want.

**Comment by jedisct1** [comment]
Ok, so we already have a IUF API :)
