### ISSUE TITLE
Error instead of panic if `KeyPair::from_seed()` receives all-zero input

### ISSUE THREAD

**Issue by brycx** [jedisct1/rust-ed25519-compact#23]
I wanted to ask before potentially opening a PR that I have halfways done. Would you be open the changing the signature of the `KeyPair::from_seed()` function to return an error instead of panicking on all-zero seed, @jedisct1? This would constitute a semver breaking-change.

I'd like it to, because I'm using `KeyPair::from_seed()` to check the public key supplied, in order to remove a possible misuse avenue in terms of a public key oracle.

**Comment by jedisct1** [comment]
I'd rather avoid a breaking change. Especially in the context of what `from_seed()` was originally designed for. If we get an all-zero seed, there's a serious issue in the application logic or a completely broken CSPRNG, and panic()ing seems like a good thing to do, rather than leaving the option of ignoring the error.

But we can add a function that explicitly does what you want to do. Validate that the key pair is valid, by recomputing its public key and comparing it with the stored one.

The most difficult part would be to find a good name for that function :)

**Comment by brycx** [comment]
> If we get an all-zero seed, there's a serious issue in the application logic or a completely broken CSPRNG, and panic()ing seems like a good thing to do, rather than leaving the option of ignoring the error.

I thought this might be the motivation behind. In the end, I can wrap it in `catch_unwind()` if needed. As a side note, this made me think then, that we're still able to construct a `SecretKey` with all-zero seed, not reaching a panic unless we call `SecretKey::seed()` at some later point. Is this also intentional, in that we expect a `SecretKey` to only be constructed from a "good" and valid set of `seed || pk`?

I've opened a PR (#24) for the addition you suggested.
